<?php
require_once '../config/db_connect.php';
include '../includes/header.php';

// Check if admin is logged in
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    header("Location: ../admin/login.php");
    exit();
}

$error = '';
$success = '';
$receipt_number = '';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $student_id = sanitize_input($_POST['student_id']);
    $fee_id = sanitize_input($_POST['fee_id']);
    $payment_date = sanitize_input($_POST['payment_date']);
    $amount_paid = sanitize_input($_POST['amount_paid']);
    $mode = sanitize_input($_POST['mode']);
    $transaction_id = sanitize_input($_POST['transaction_id']);
    $remarks = sanitize_input($_POST['remarks']);
    
    if (empty($student_id) || empty($fee_id) || empty($payment_date) || empty($amount_paid) || empty($mode)) {
        $error = "All required fields must be filled.";
    } elseif ($amount_paid <= 0) {
        $error = "Amount must be greater than 0.";
    } else {
        // Insert payment
        $query = "INSERT INTO payment (student_id, fee_id, payment_date, amount_paid, mode, status, transaction_id, remarks) 
                  VALUES ($student_id, $fee_id, '$payment_date', $amount_paid, '$mode', 'Completed', '$transaction_id', '$remarks')";
        
        if (execute_query($query)) {
            $payment_id = get_last_id();
            
            // Get receipt number (auto-generated by trigger)
            $receipt = fetch_single("SELECT receipt_number FROM receipt WHERE payment_id = $payment_id");
            $receipt_number = $receipt ? $receipt['receipt_number'] : '';
            
            $success = "Payment recorded successfully! Payment ID: $payment_id";
            if ($receipt_number) {
                $success .= " | Receipt Number: $receipt_number";
            }
            
            // Clear form
            $_POST = array();
        } else {
            $error = "Failed to record payment.";
        }
    }
}

// Get all students for dropdown
$students = fetch_all("
    SELECT s.*, c.course_name 
    FROM students s 
    INNER JOIN courses c ON s.course_id = c.course_id 
    ORDER BY s.name
");
?>

<h2>💳 Make Payment</h2>

<?php if ($error): ?>
    <div class="alert alert-error"><?php echo $error; ?></div>
<?php endif; ?>

<?php if ($success): ?>
    <div class="alert alert-success">
        <?php echo $success; ?>
        <?php if ($receipt_number): ?>
            <br><a href="generate_receipt.php?receipt=<?php echo $receipt_number; ?>" target="_blank" class="btn" style="margin-top: 10px;">View Receipt</a>
        <?php endif; ?>
    </div>
<?php endif; ?>

<div class="card">
    <form method="POST" action="" id="paymentForm">
        <div class="form-group">
            <label for="student_id">Select Student *</label>
            <select id="student_id" name="student_id" required onchange="loadFeeStructure(this.value)">
                <option value="">-- Select Student --</option>
                <?php foreach ($students as $student): ?>
                    <option value="<?php echo $student['student_id']; ?>">
                        <?php echo htmlspecialchars($student['name']); ?> - 
                        <?php echo htmlspecialchars($student['course_name']); ?> 
                        (<?php echo $student['email']; ?>)
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        
        <div class="form-group">
            <label for="fee_id">Select Semester Fee *</label>
            <select id="fee_id" name="fee_id" required onchange="updateAmount()">
                <option value="">-- Select Student First --</option>
            </select>
        </div>
        
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px;">
            <div class="form-group">
                <label for="payment_date">Payment Date *</label>
                <input type="date" id="payment_date" name="payment_date" required 
                       value="<?php echo date('Y-m-d'); ?>">
            </div>
            
            <div class="form-group">
                <label for="amount_paid">Amount Paid (₹) *</label>
                <input type="number" id="amount_paid" name="amount_paid" required min="0" step="0.01">
            </div>
            
            <div class="form-group">
                <label for="mode">Payment Mode *</label>
                <select id="mode" name="mode" required>
                    <option value="">-- Select Mode --</option>
                    <option value="Cash">Cash</option>
                    <option value="Card">Card</option>
                    <option value="UPI">UPI</option>
                    <option value="Net Banking">Net Banking</option>
                    <option value="Cheque">Cheque</option>
                </select>
            </div>
            
            <div class="form-group">
                <label for="transaction_id">Transaction ID</label>
                <input type="text" id="transaction_id" name="transaction_id">
            </div>
        </div>
        
        <div class="form-group">
            <label for="remarks">Remarks</label>
            <textarea id="remarks" name="remarks" rows="3"></textarea>
        </div>
        
        <button type="submit" class="btn">Record Payment</button>
        <a href="view_payments.php" class="btn btn-secondary" style="margin-left: 10px; display: inline-block; text-decoration: none; text-align: center;">View All Payments</a>
    </form>
</div>

<script>
function loadFeeStructure(studentId) {
    if (!studentId) {
        document.getElementById('fee_id').innerHTML = '<option value="">-- Select Student First --</option>';
        return;
    }
    
    // AJAX call to get fee structure for student's course
    fetch('get_fee_structure.php?student_id=' + studentId)
        .then(response => response.json())
        .then(data => {
            let options = '<option value="">-- Select Semester --</option>';
            data.forEach(fee => {
                options += `<option value="${fee.fee_id}" data-amount="${fee.amount}">
                    Semester ${fee.semester} - ₹${parseFloat(fee.amount).toFixed(2)} - ${fee.description}
                </option>`;
            });
            document.getElementById('fee_id').innerHTML = options;
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Failed to load fee structure');
        });
}

function updateAmount() {
    const feeSelect = document.getElementById('fee_id');
    const selectedOption = feeSelect.options[feeSelect.selectedIndex];
    const amount = selectedOption.getAttribute('data-amount');
    
    if (amount) {
        document.getElementById('amount_paid').value = parseFloat(amount).toFixed(2);
    }
}
</script>

<?php
include '../includes/footer.php';
?>
